# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NodeCast
email: nodecastmt@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   An Unofficial Minetest Podcast
domain: exevirus.github.io
baseurl: "/nodecast" # the subpath of your site, e.g. /blog
url: "https://exevirus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ExeVirus
future: true

# Build settings
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed

# Podcast Settings
podcast_url: https://exevirus.github.io/nodecast/
podcast_album_art: /assets/img/nodecast.jpg
podcast_title: Nodecast
podcast_owner: JExeVirus
podcast_email: nodecastmt@gmail.com
podcast_category: Games
podcast_subcategory_one: Technology
podcast_subcategory_two: Open Source
podcast_explicit: "no"
podcast_author: ExeVirus
podcast_description: A Rolling release, interview-centered Minetest podcast
podcast_summary: A Rolling release, interview-centered podcast all about being a player, community member, modder, and just about everything else in the Minetest world!
podcast_subtitle: The Unnofficial Minetest Podcast

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
