# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NodeCast
email: nodecastmt@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   An Unofficial Minetest Podcast
domain: exevirus.github.io
baseurl: "/nodecast" # the subpath of your site, e.g. /blog
url: "https://exevirus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ExeVirus
future: true

# Build settings
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed

# Podcast Settings
podcast_url: http://
podcast_album_art: /assets/base/Whaddya-Know-Joe-Album-Art.png
podcast_title: Whaddya Know Joe?
podcast_owner: Joe Buhlig
podcast_email: email@example.com
podcast_category: Technology
podcast_subcategory_one: Software How-To
podcast_subcategory_two: Gadgets
podcast_explicit: "no"
podcast_author: Joe Buhlig
podcast_description: Productivity stories from the trenches. What works and what I'll never do again. Hosted by Joe Buhlig.
podcast_summary: Joe Buhlig walks you through real life story and then breaks down the productivity tools and techniques used. It's a great way to learn how to implement the tips and tricks that you see across the web. Productivity stories from the trenches. What works and what to never try.
podcast_subtitle: Productivity stories from the trenches. What works and what I'll never do again. Hosted by Joe Buhlig.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
